# Generated by Django 6.0.8 on 2026-09-16 06:24

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
